=== alexandrepiveteau/heig-SER-labo01/src/main/resources/easychess.dtd
<!ELEMENT easy-chess (player*, tournament*)>

  <!-- MARK : Player definitions. -->
  <!-- NOTE : Players are shared amongst the different tournaments, since
  they're part of a single club. -->
  <!ELEMENT player (name, elo-ranking)>
  <!ATTLIST player ssn ID #REQUIRED>
  <!ELEMENT name (first-name, last-name)>
  <!ELEMENT first-name (#PCDATA)>
  <!ELEMENT last-name (#PCDATA)>
  <!ELEMENT elo-ranking (#PCDATA)>

  <!-- MARK : Tournaments and games. -->
  <!ELEMENT tournament (team, team, team*, game, game*)>
  <!ATTLIST tournament winner IDREF #REQUIRED>
  <!ELEMENT game (date, referee, moves)>
  <!ATTLIST game team-one IDREF #REQUIRED>
  <!ATTLIST game team-one-score (0|0.5|1|1.5|2) #REQUIRED>
  <!ATTLIST game team-two IDREF #REQUIRED>
  <!ATTLIST game team-two-score (0|0.5|1|1.5|2) #REQUIRED>

  <!-- MARK : Dates and time definitions. -->
  <!ELEMENT date EMPTY>
  <!ATTLIST date hour CDATA #REQUIRED>
  <!ATTLIST date day CDATA #REQUIRED>
  <!ATTLIST date month (jan|feb|mar|apr|may|jun|jul|aug|set|nov|dec) #REQUIRED>
  <!ATTLIST date year CDATA #REQUIRED>

  <!-- MARK : Teams definitions. -->
  <!ELEMENT team (teammate, teammate)>
  <!ATTLIST team id ID #REQUIRED>
  <!ELEMENT teammate EMPTY>
  <!ATTLIST teammate person IDREF #REQUIRED>

  <!ELEMENT referee (name)>

  <!-- MARK : Possible moves in a game -->
  <!ELEMENT moves (move|castling)*>
  <!ELEMENT move (cell, cell?)>
  <!ATTLIST move board (A|B) #REQUIRED>
  <!ATTLIST move type (pawn|rook|knight|bishop|queen|king) #REQUIRED>
  <!ATTLIST move takes (pawn|rook|knight|bishop|queen) #IMPLIED>
  <!ATTLIST move promotion (rook|knight|bishop|queen) #IMPLIED>
  <!ATTLIST move accouncement (checkmate|check|draw) #IMPLIED>
  <!ELEMENT castling (cell, cell?)>
  <!ATTLIST castling board (A|B) #REQUIRED>
  <!ATTLIST castling type (small|big) #REQUIRED>

  <!-- MARK : Cells and their possible attributes. -->
  <!ELEMENT cell EMPTY>
  <!ATTLIST cell x (A|B|C|D|E|F|G|H) #REQUIRED>
  <!ATTLIST cell y (1|2|3|4|5|6|7|8) #REQUIRED>

=== alexandrepiveteau/heig-SER-labo01/src/main/resources/easychess.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE easy-chess SYSTEM "easychess.dtd">
<easy-chess>

  <player ssn="Ssn1">
    <first-name>Stacy</first-name>
    <last-name>Waller</last-name>
    <elo-ranking>1700</elo-ranking>
  </player>

  <player ssn="Ssn2">
    <first-name>Hashir</first-name>
    <last-name>Avila</last-name>
    <elo-ranking>1800</elo-ranking>
  </player>

  <player ssn="Ssn3">
    <first-name>Lucas</first-name>
    <last-name>Horner</last-name>
    <elo-ranking>1654</elo-ranking>
  </player>

  <player ssn="Ssn4">
    <first-name>Sienna</first-name>
    <last-name>Hart</last-name>
    <elo-ranking>1864</elo-ranking>
  </player>

  <tournament winner="Team1">

    <team id="Team1">
      <teammate person="Ssn1"/>
      <teammate person="Ssn2"/>
    </team>

    <team id="Team2">
      <teammate person="Ssn3"/>
      <teammate person="Ssn4"/>
    </team>

    <game
      team-one="Team2"
      team-one-score="1"
      team-two="Team2"
      team-two-score="1">

      <date hour="14:05" day="01" month="jan" year="2020"/>

      <referee>
        <first-name>Maria</first-name>
        <last-name>Wills</last-name>
      </referee>

      <moves>
        <move type="pawn" board="A">
          <cell x="A" y="3"/>
        </move>
        <move type="pawn" accouncement="check" takes="pawn" board="B">
          <cell x="A" y="5"/>
        </move>
        <castling type="big" board="B">
          <cell x="B" y="4"/>
        </castling>
      </moves>

    </game>

  </tournament>

</easy-chess>
